version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql
    build: ./mysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql  # Persistence
      - ./mysql/sqls:/docker-entrypoint-initdb.d  # initial data
    ports:
     - 3306:3306
    environment:
        MYSQL_DATABASE: family
        MYSQL_ROOT_PASSWORD: family
  coin-api:
    container_name: coin-api
    image: coin-api
    build:
      context: ./coin-api
    volumes:
      - ./coin-api:/coin-api
      - /coin-api/node_modules
    ports:
      - "18080:18080"
    links:
      - mysql
  coin-app:
    container_name: coin-app
    image: coin-app
    build:
      context: ./coin-app
    volumes:
      - ./coin-app:/coin-app
      - /coin-app/vue-element-admin/node_modules
    ports:
      - "9527:9527"
  coin-batch:
    container_name: coin-batch
    image: coin-batch
    build:
      context: ./coin-batch
    volumes:
      - ./coin-batch:/coin-batch
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=family
    links:
      - mysql
    ports:
       - 8080:80
    volumes:
       - "./phpmyadmin/sessions:/sessions"
