version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql
    build: ./mysql
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql  # Persistence
      - ./mysql/sqls:/docker-entrypoint-initdb.d  # initial data
    ports:
     - 3306:3306
    environment:
        MYSQL_DATABASE: family
        MYSQL_ROOT_PASSWORD: family
  coin-api:
    container_name: coin-api
    image: coin-api
    build:
      context: ./coin-api
    volumes:
      - ./coin-api:/coin-api
      - /coin-api/node_modules
    ports:
      - "18080:18080"
  coin-app:
    container_name: coin-app
    image: coin-app
    build:
      context: ./coin-app
    volumes:
      - ./coin-app:/coin-app
      - /coin-app/node_modules
    ports:
      - "8080:8080"
